<h1>Modifier un utilisateur</h1>
<p>Shalom haver shli, Salom saahebi</p>

<form action='index.php?route=check_update_user' method='POST'>
    <input type="hidden" name="id" value="<?= $user->getId() ?>"/>
    
    <label for="email">Email :</label>
    <input type='email' id='email' name='email' value='<?= htmlspecialchars($user->getEmail()) ?>' required>
    
    <label for="first_name">Prénom :</label>
    <input type='text' id='first_name' name='first_name' value='<?= htmlspecialchars($user->getFirstName()) ?>' required>
    
    <label for="last_name">Nom :</label>
    <input type='text' id='last_name' name='last_name' value='<?= htmlspecialchars($user->getLastName()) ?>' required>
    
    <input type="submit" value="Enregistrer les modifications"/>
</form>

<a href='index.php'>Retour à la liste</a>